services:
  - type: web
    name: schoolpilot-be
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - fromGroup: schoolpilot-secrets
