import { InputType, Field } from '@nestjs/graphql';
import { IsNotEmpty, IsOptional, IsEnum, IsDateString } from 'class-validator';
import { Transform } from 'class-transformer';
import { Gender, StudentStatus } from '../../common/enums';

@InputType()
export class CreateStudentInput {
  @Field()
  @IsNotEmpty()
  firstName!: string;

  @Field({ nullable: true })
  @IsOptional()
  middleName?: string;

  @Field()
  @IsNotEmpty()
  lastName!: string;

  @Field({
    nullable: true,
    deprecationReason: 'Admission number is now auto-generated by the server',
  })
  @IsOptional()
  admissionNumber?: string;

  @Field({ nullable: true })
  @IsOptional()
  @Transform(({ value }) => (value === '' ? undefined : value))
  @IsDateString()
  dateOfBirth?: string;

  @Field(() => Gender)
  @IsEnum(Gender)
  gender!: Gender;

  @Field({ nullable: true })
  @IsOptional()
  nationality?: string;

  @Field({ nullable: true })
  @IsOptional()
  stateOfOrigin?: string;

  @Field({ nullable: true })
  @IsOptional()
  lga?: string;

  @Field(() => StudentStatus, { nullable: true })
  @IsOptional()
  @IsEnum(StudentStatus)
  status?: StudentStatus;

  @Field({ nullable: true })
  @IsOptional()
  @Transform(({ value }) => (value === '' ? undefined : value))
  @IsDateString()
  dateOfAdmission?: string;

  @Field({ nullable: true })
  @IsOptional()
  admissionClassId?: string;

  @Field()
  @IsNotEmpty()
  classId!: string;

  @Field({ nullable: true })
  @IsOptional()
  address?: string;

  @Field({ nullable: true })
  @IsOptional()
  medicalInfo?: string;

  @Field({ nullable: true })
  @IsOptional()
  notes?: string;

  @Field({ nullable: true })
  @IsOptional()
  passportPhotoUrl?: string;

  @Field({ nullable: true })
  @IsOptional()
  parentPhone?: string;
}
